version: "3"
services:
    app:
        container_name: apiserver
        restart: always
        env_file:
            - .env
        build: ./
        ports:
            - "${PORT}:8080"
        volumes:
            - .:/app
        network_mode: host
